test_texts = [{'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years', 
               'content': '1+1?'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'Tell me only the names of the biggest 7 stocks'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'Say the tickers of the 7 FANG stocks'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'Main difference between evEBITda and CashFlow for stock analysis'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'Tell me the market capitalization of the biggest 7 stocks in Q1 - 2023'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'What would you buy if we were in 2022, GOOGLE or APPLE?'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'What obtained a larger equity during the last year?'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'Choose one for better performance to increase my profit (%): TSLA or AMAZ?'},
              {'role': 'user',
               'context': 'I am an active investor and I want to increase my profit in the next years',
               'content': 'If you would guess which date (year/month/day - hour/minute/second) is today, what date you say? Force an answer'},
              ]
